### ISSUE TITLE
Rethinking CouchDB testing and deploying

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/couchdb-config#2]
Our current solution for writing, testing, and deploying CouchDB views needs refinement. Ideally, working on CouchDB JavaScript functionality should occur under TDD paradigms. There are two ways to think about testing these functions:

1. The functions are tested outside of a CouchDB context.
2. The functions are imported into a test CouchDB installation, and tests make HTTP calls to that installation.

We've chosen the latter approach. Another question is whether or not all CouchDB view config should live in one central repository, or one repository per database. If we go in the latter direction, test scaffolding code should live in its own repository and be included into the database repositories.

It might be nice to think about how this would work in a world where we're running this through CI.

**Comment by RussellMcOrmond** [comment]
I believe we should include the schema documentation in this conversation.  Currently the individual CouchDB databases have documentation of fields/views/etc in a Google Document, but there is logic in all of this accompanying the code.

**Comment by SaschaAdler** [comment]
I agree. Would we want to use [JSON Schema](https://json-schema.org/)? (See: [ajv](https://ajv.js.org/))

**Comment by SaschaAdler** [comment]
We've moved forward significantly on this; see what kivik can do now.
